apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prod-redis
  name: prod-redis
spec:
  selector:
    matchLabels:
      run: prod-redis
  replicas: 3
  minReadySeconds: 300
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: prod-redis
    spec:
      containers:
      - image: redis:4.0
        name: redis
